#!/bin/sh
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
SCRIPT_NAME=$(basename $0)
MPIEXEC_PATH="$1"
MPIEXEC_NP_FLAG="$2"
MPIEXEC_PREFLAGS="$3"
TEST_BINARY_PATH="$4"
TEST_INPUT_DATA_PATH="$5"
TEST_SCRIPTS_PATH="$6"
final_exit_code=0
DIR=$(dirname "$TEST_BINARY_PATH")
echo "$DIR"
TMP_OUTPUT="tmp_output_""$SCRIPT_NAME"

# Load FEMPAR CLAs
. $TEST_SCRIPTS_PATH/fempar_parameters

# Allowed variation (%) in the number of iterations  w.r.t. the reference solution to return a PASSED test
allowed_variation=0.05 
final_exit_code=0

if [ -d "$DIR" ]
then
    if [ -f "$TEST_BINARY_PATH" ]
    then
        if [ -d "$TEST_INPUT_DATA_PATH" ] 
        then
            # test 1 - Analytical known function test with unit constant coefficients
            echo "$MPIEXEC_PATH $MPIEXEC_NP_FLAG 9 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $triang_generate_flag 1 $prefix_flag 'square' $struct_hex_triang_num_dims_flag 3 $struct_hex_triang_num_cells_dir_flag 6 6 6 $struct_hex_triang_num_parts_x_dir_flag 2 2 2 1 1 1 $struct_hex_triang_num_levels_flag 2 -order 1 -wsolution .false. -edge_cont tangential_average_and_first_order_moment -materials_case homogeneous -bddc_weights cardinality -bmass_trick .false. -coefficient_case unit_constant" 
            $MPIEXEC_PATH $MPIEXEC_NP_FLAG 9 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $triang_generate_flag 1 $prefix_flag 'square' $struct_hex_triang_num_dims_flag 3 $struct_hex_triang_num_cells_dir_flag 6 6 6 $struct_hex_triang_num_parts_x_dir_flag 2 2 2 1 1 1 $struct_hex_triang_num_levels_flag 2 -order 1 -wsolution .false. -edge_cont tangential_average_and_first_order_moment -materials_case homogeneous -bddc_weights cardinality -bmass_trick .false. -coefficient_case unit_constant
 

            #test 2 - Unknown solution w/ checkerboard distrib. of materials ------------------------------
            echo "$MPIEXEC_PATH $MPIEXEC_NP_FLAG 9 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $triang_generate_flag 1 $prefix_flag 'square' $struct_hex_triang_num_dims_flag 3 $struct_hex_triang_num_cells_dir_flag 8 8 8 $struct_hex_triang_num_parts_x_dir_flag 2 2 2 1 1 1 $struct_hex_triang_num_levels_flag 2 $coarse_space_use_faces_flag .false. -order 1 -wsolution .false. -edge_cont tangential_average_and_first_order_moment -mass_coeff_white 1.0 -curl_curl_coeff_white 1e2 -mass_coeff_black 1e-2 -curl_curl_coeff_black 1e4 -materials_case checkerboard -bddc_weights curl_curl_coeff -bmass_trick .true. -coefficient_case constant | tee $TMP_OUTPUT"
            $MPIEXEC_PATH $MPIEXEC_NP_FLAG 9 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $triang_generate_flag 1 $prefix_flag 'square' $struct_hex_triang_num_dims_flag 3 $struct_hex_triang_num_cells_dir_flag 8 8 8 $struct_hex_triang_num_parts_x_dir_flag 2 2 2 1 1 1 $struct_hex_triang_num_levels_flag 2 $coarse_space_use_faces_flag .false. -order 1 -wsolution .false. -edge_cont tangential_average_and_first_order_moment -mass_coeff_white 1.0 -curl_curl_coeff_white 1e2 -mass_coeff_black 1e-2 -curl_curl_coeff_black 1e4 -materials_case checkerboard -bddc_weights curl_curl_coeff -bmass_trick .true. -coefficient_case constant | tee $TMP_OUTPUT

            # Check Number of iterations is within allowed range º
            exit_code1=0
            n1=$(grep "CG converged to " $TMP_OUTPUT |sed s/" "" "*/"#"/g|cut -f6 -d#)
            n2=$(grep "CG converged to " $TEST_INPUT_DATA_PATH/test2_convergence_fast |sed s/" "" "*/"#"/g|cut -f6 -d#)
            if [ $(python -c "print \"%d\" % (1 if abs($n1-$n2)>$allowed_variation*$n2 else 0)") = 1 ]; then 
                final_exit_code=1
            fi 
            rm -f $TMP_OUTPUT  
   

            #test 3 - Unknown solution w/ analytical functions describing coeffs ---------------------------------
            echo "$MPIEXEC_PATH $MPIEXEC_NP_FLAG 9 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $triang_generate_flag 1 $prefix_flag 'square' $struct_hex_triang_num_dims_flag 3 $struct_hex_triang_num_cells_dir_flag 12 12 12 $struct_hex_triang_num_parts_x_dir_flag 2 2 2 1 1 1 $struct_hex_triang_num_levels_flag 2 $coarse_space_use_faces_flag .false. -order 1 -wsolution .false. -edge_cont tangential_average_and_first_order_moment -materials_case heterogeneous -bddc_weights weighted_coefficients -bmass_trick .false. -rpb_bddc_threshold 1e3 -coefficient_case sinusoidal -mass_coeff_white 3 -curl_curl_coeff_white 3 -num_peaks_curl_curl_coeff 2 -num_peaks_mass_coeff 2  | tee $TMP_OUTPUT" 
            $MPIEXEC_PATH $MPIEXEC_NP_FLAG 9 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $triang_generate_flag 1 $prefix_flag 'square' $struct_hex_triang_num_dims_flag 3 $struct_hex_triang_num_cells_dir_flag 12 12 12 $struct_hex_triang_num_parts_x_dir_flag 2 2 2 1 1 1 $struct_hex_triang_num_levels_flag 2 $coarse_space_use_faces_flag .false. -order 1 -wsolution .false. -edge_cont tangential_average_and_first_order_moment -materials_case heterogeneous -bddc_weights weighted_coefficients -bmass_trick .false. -rpb_bddc_threshold 1e3 -coefficient_case sinusoidal -mass_coeff_white 3 -curl_curl_coeff_white 3 -num_peaks_curl_curl_coeff 2 -num_peaks_mass_coeff 2  | tee $TMP_OUTPUT

            # Check Number of iterations within allowed range 
            exit_code1=0
            n1=$(grep "CG converged to " $TMP_OUTPUT |sed s/" "" "*/"#"/g|cut -f6 -d#)
            n2=$(grep "CG converged to " $TEST_INPUT_DATA_PATH/test3_convergence_fast |sed s/" "" "*/"#"/g|cut -f6 -d#)
            if [ $(python -c "print \"%d\" % (1 if abs($n1-$n2)>$allowed_variation*$n2 else 0)") = 1 ]; then 
                final_exit_code=1
            fi 
            rm -f $TMP_OUTPUT 

        else
            echo "$0: input data directory not found!"
            final_exit_code=1
        fi
    else
      echo "$0: BINARY not found! Value PROVIDED: $4."
      final_exit_code=1
    fi
else
  echo "$0: PART not found! Value PROVIDED: $DIR/part."
  final_exit_code=1
fi
rm -Rf $TEST_COMBINATIONS_FILE_NAME
exit $final_exit_code 
