#!/bin/bash
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
MPIEXEC_PATH="$1"
MPIEXEC_NP_FLAG="$2"
MPIEXEC_PREFLAGS="$3"
TEST_BINARY_PATH="$4"
TEST_INPUT_DATA_PATH="$5"
TEST_SCRIPTS_PATH="$6"
final_exit_code=0
DIR=$(dirname "$TEST_BINARY_PATH")
echo "$DIR"

# Load FEMPAR CLAs
. $TEST_SCRIPTS_PATH/fempar_cla_names

lst_integration_schemes="forward_euler#backward_euler#trapezoidal_rule#mid_point_implicit#mid_point_explicit#imex_rk_2_2_1_implicit#imex_rk_2_2_1_explicit#imex_rk_2_2_2_implicit#imex_rk_2_2_2_explicit#imex_rk_2_3_implicit#imex_rk_2_3_explicit#runge_kutta_3#runge_kutta_4#runge_kutta_4_3_8#imex_rk_4_3_implicit#imex_rk_4_3_explicit"

num_integration_schemes=16

if [ -f "$TEST_BINARY_PATH" ]
then
# if [ -d "$TEST_INPUT_DATA_PATH" ] 
#   then
      ###############################################################################################################################
      # Convergence order tests of transient poisson
      ###############################################################################################################################

      id_scheme=1
      while [ $id_scheme -le $num_integration_schemes ]
      do 
          integration_scheme=$(echo $lst_integration_schemes|cut -f$id_scheme -d#)
           
          if [ "$(echo $integration_scheme | grep -E 'runge_kutta|imex_rk_4_3|trapezoidal')" == "" ]
          then
              COMMAND="$MPIEXEC_PATH $MPIEXEC_NP_FLAG 10 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $environment_num_levels_flag 2 $environment_num_tasks_x_level_flag 9 1 $static_triang_generate_from_flag STRUCT_HEX_MESH_GENERATOR $struct_hex_mesh_generator_num_parts_x_dim_x_level_flag 3 3 1 1 $struct_hex_mesh_generator_num_cells_x_dim_flag 12 12 $struct_hex_mesh_generator_domain_limits_flag 0.0 1.0 0.0 1.0 -rk-scheme $integration_scheme -test .true. -tf 0"
              echo $COMMAND
              eval $COMMAND
              if [ $? -ne 0 ]
              then
                final_exit_code=1
                break 1
              fi
          fi
          if [ "$(echo $integration_scheme | grep -E 'backward|implicit')" != "" ]
          then
            COMMAND="$MPIEXEC_PATH $MPIEXEC_NP_FLAG 5 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $environment_num_levels_flag 2 $environment_num_tasks_x_level_flag 4 1 $static_triang_generate_from_flag STRUCT_HEX_MESH_GENERATOR $struct_hex_mesh_generator_num_parts_x_dim_x_level_flag 2 2 1 1 $struct_hex_mesh_generator_num_cells_x_dim_flag 8 8 $struct_hex_mesh_generator_domain_limits_flag 0.0 1.0 0.0 1.0 -rk-scheme $integration_scheme -dt 1 -tf 10"
            echo $COMMAND
            eval $COMMAND
            if [ $? -ne 0 ]
            then
              final_exit_code=1
              break 1
            fi

            COMMAND="$MPIEXEC_PATH $MPIEXEC_NP_FLAG 10 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $environment_num_levels_flag 2 $environment_num_tasks_x_level_flag 9 1 $static_triang_generate_from_flag STRUCT_HEX_MESH_GENERATOR $struct_hex_mesh_generator_num_parts_x_dim_x_level_flag 3 3 1 1 $struct_hex_mesh_generator_num_cells_x_dim_flag 12 12 $struct_hex_mesh_generator_domain_limits_flag 0.0 1.0 0.0 1.0 -rk-scheme $integration_scheme -dt 0.1 -tf 0.5"
            echo $COMMAND
            eval $COMMAND
            if [ $? -ne 0 ]
            then
              final_exit_code=1
              break 1
            fi
          fi
      let id_scheme=id_scheme+1
      done

else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code
