#!/bin/sh
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
MPIEXEC_PATH="$1"
MPIEXEC_NP_FLAG="$2"
MPIEXEC_PREFLAGS="$3"
TEST_BINARY_PATH="$4"
TEST_INPUT_DATA_PATH="$5"
TEST_SCRIPTS_PATH="$6"
final_exit_code=0
DIR=$(dirname "$TEST_BINARY_PATH")

# Load FEMPAR CLAs
. $TEST_SCRIPTS_PATH/fempar_cla_names

if [ -f "$TEST_BINARY_PATH" ]
then

  if [ $final_exit_code -eq 0 ] 
  then
   for order in 1 #2 3 
   do
     COMMAND="$MPIEXEC_PATH $MPIEXEC_NP_FLAG 5 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $environment_num_levels_flag 2 $environment_num_tasks_x_level_flag 4 1 -order $order"
     echo $COMMAND
     eval $COMMAND
     if [ $? -ne 0 ] 
     then
      final_exit_code=1
      break 1
     fi

     COMMAND="$MPIEXEC_PATH $MPIEXEC_NP_FLAG 7 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $environment_num_levels_flag 2 $environment_num_tasks_x_level_flag 6 1 -order $order"
     echo $COMMAND
     eval $COMMAND
     if [ $? -ne 0 ]
     then
      final_exit_code=1
      break 1
     fi
   done  
  fi

  if [ $final_exit_code -eq 0 ] 
  then
   for order in 1 #2
   do
     COMMAND="$MPIEXEC_PATH $MPIEXEC_NP_FLAG 5 $MPIEXEC_PREFLAGS $TEST_BINARY_PATH $environment_num_levels_flag 2 $environment_num_tasks_x_level_flag 4 1 -order $order"
     echo $COMMAND
     eval $COMMAND
     if [ $? -ne 0 ] 
     then
      final_exit_code=1
      break 1
     fi
   done  
  fi
else
  echo "$0: BINARY not found! Value PROVIDED: $4."
  final_exit_code=1
fi

rm -Rf $TEST_COMBINATIONS_FILE_NAME
exit $final_exit_code 

