#!/bin/sh
TEST_BINARY_PATH="$1"
TEST_INPUT_DATA_PATH="$2"
final_exit_code=0
if [ -f "$TEST_BINARY_PATH" ]
then
 if [ -d "$TEST_INPUT_DATA_PATH" ] 
   then
      # Square + Quads        
      for gorder in 1 2 3 4 5 6
      do
       for order in 1 2 3 4 5 6
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH --dir-path $TEST_INPUT_DATA_PATH/square_quads.gid --prefix square_quads -order $order -gorder $gorder"
            $TEST_BINARY_PATH --dir-path $TEST_INPUT_DATA_PATH/square_quads.gid --prefix square_quads -order $order -gorder $gorder 
            if [ $? -ne 0 ] 
            then
             final_exit_code=1
            fi
          fi
        done
      done

      # Circle + Quads        
      for gorder in 1 2 3 4 5 6
      do
       for order in 1 2 3 4 5 6
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH --dir-path $TEST_INPUT_DATA_PATH/circle.gid --prefix circle -order $order -gorder $gorder"
            $TEST_BINARY_PATH --dir-path $TEST_INPUT_DATA_PATH/circle.gid --prefix circle -order $order -gorder $gorder
            if [ $? -ne 0 ]
            then
             final_exit_code=1
            fi
          fi
        done
      done

      # Square +  Tetrahedra       
      for gorder in 1 #2 3 4 5 6
      do
       for order in 1 2 3 #4 5 6
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH --dir-path $TEST_INPUT_DATA_PATH/square_tetrahedra.gid --prefix square_tetrahedra -order $order -gorder $gorder"
            $TEST_BINARY_PATH --dir-path $TEST_INPUT_DATA_PATH/square_tetrahedra.gid --prefix square_tetrahedra -order $order -gorder $gorder
            if [ $? -ne 0 ]
            then
             final_exit_code=1
            fi
          fi
        done
      done





   else
      echo "$0: input data directory not found!"
      final_exit_code=1
   fi
else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code
