#!/bin/sh
SCRIPT_NAME=$(basename $0)
TEST_BINARY_PATH="$1"
TEST_INPUT_DATA_PATH="$2"
TEST_SCRIPTS_PATH="$3"
final_exit_code=0

# Load FEMPAR CLAs
. $TEST_SCRIPTS_PATH/fempar_parameters

if [ -f "$TEST_BINARY_PATH" ]
then

    ###############################################################################################################################
    # Scalar-valued tests
    ###############################################################################################################################

    if [ $final_exit_code -eq 0 ] 
    then    
      vbcs="diri"
      vmts="aggr stnd"
      vods="1 2"
      vdim="2 3"
      vpat="uniform"  ## debug-1 debug-2"
      
      ilvs=2
      for idim in $vdim; do
        for iods in $vods; do
          for ibcs in $vbcs; do
            for imts in $vmts; do
              for ipat in $vpat; do
                if [ $idim -ne 3 -o $iods -ne 2 ] ; then
        
                  prefix=${imts}_${ipat}_${ibcs}_l${ilvs}_p${iods}
        
                  is_diri=".true."
                  if [ $ibcs = neum ]; then
                    is_diri="false"
                  fi
        
                  uconstraints=".true."
                  is_bconst=".true."
                  if [ $imts = stnd ]; then
                    uconstraints=".false."
                    is_bconst=".false."
                  fi

                  sdiri=".false."
                  dom="0.0 1.0"
                  if [ $ipat = "debug-1" ]; then
                    sdiri=".false."
                    dom="-1.0 1.0"
                  fi
        
                  cmd="$TEST_BINARY_PATH $triang_generate_flag 1 $struct_hex_triang_num_dims_flag $idim -rpattern $ipat -sdiri $sdiri -dom $dom -wsolution .false. -order $iods -in_space .true.  -check .true. -maxl $ilvs -wmatrix .false. -uconstraints $uconstraints -is_diri $is_diri -is_bconst $is_bconst $dir_path_out_flag $SCRIPT_NAME $prefix_flag $SCRIPT_NAME"
        
                  echo $cmd
                  $cmd
                  if [ $? -ne 0 ] 
                  then
                   final_exit_code=1
                   break 5
                  fi
        
                fi
              done
            done
          done
        done
      done
    fi

    ###############################################################################################################################
    # Vector-valued tests
    ###############################################################################################################################

    if [ $final_exit_code -eq 0 ] 
    then          
      vbcs="diri"
      vmts="aggr stnd"
      vods="2"
      vdim="2"
      vpat="uniform"  ## debug-1 debug-2"
      
      ilvs=2
      for idim in $vdim; do
        for iods in $vods; do
          for ibcs in $vbcs; do
            for imts in $vmts; do
              for ipat in $vpat; do
                if [ $idim -ne 3 -o $iods -ne 2 ] ; then
        
                  prefix=${imts}_${ipat}_${ibcs}_l${ilvs}_p${iods}
        
                  is_diri=".true."
                  if [ $ibcs = neum ]; then
                    is_diri="false"
                  fi
        
                  uconstraints=".true."
                  is_bconst=".true."
                  if [ $imts = stnd ]; then
                    uconstraints=".false."
                    is_bconst=".false."
                  fi

                  sdiri=".false."
                  dom="0.0 1.0"
                  if [ $ipat = "debug-1" ]; then
                    sdiri=".false."
                    dom="-1.0 1.0"
                  fi
        
                  cmd="$TEST_BINARY_PATH $triang_generate_flag 1 $struct_hex_triang_num_dims_flag $idim -rpattern $ipat -sdiri $sdiri -dom $dom -wsolution .false. -order $iods -in_space .true.  -check .true. -maxl $ilvs -wmatrix .false. -uconstraints $uconstraints -is_diri $is_diri -is_bconst $is_bconst -lt vector $dir_path_out_flag $SCRIPT_NAME $prefix_flag $SCRIPT_NAME"
        
                  echo $cmd
                  $cmd
                  if [ $? -ne 0 ] 
                  then
                   final_exit_code=1
                   break 5
                  fi
        
                fi
              done
            done
          done
        done
      done
    fi

else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code
