#!/bin/sh
SCRIPT_NAME=$(basename $0)
TEST_BINARY_PATH="$1"
TEST_INPUT_DATA_PATH="$2"
TEST_SCRIPTS_PATH="$3"
final_exit_code=0

# Load FEMPAR CLAs
. $TEST_SCRIPTS_PATH/fempar_cla_names

if [ -f "$TEST_BINARY_PATH" ]
then

    ###############################################################################################################################
    # Scalar-valued tests
    ###############################################################################################################################

    if [ $final_exit_code -eq 0 ] 
    then    
      vbcs="diri neum"
      vmts="stnd aggr"
      vods="1 2"
      vdim="2 3"
      
      ilvs=2
      for idim in $vdim; do
        if [ $idim -eq 2 ]; then
          domain_limits="0.0 1.0 0.0 1.0"
        else
          domain_limits="0.0 1.0 0.0 1.0 0.0 1.0"
        fi
        for iods in $vods; do
          for ibcs in $vbcs; do
            for imts in $vmts; do
              if [ $idim -ne 3 -o $iods -ne 2 ] ; then
        
                prefix=${imts}_${ibcs}_l${ilvs}_p${iods}
        
                is_diri=".true."
                if [ $ibcs = neum ]; then
                  is_diri="false"
                fi
        
                uconstraints=".true."
                is_bconst=".true."
                if [ $imts = stnd ]; then
                  uconstraints=".false."
                  is_bconst=".false."
                fi
        
                COMMAND="$TEST_BINARY_PATH $p4est_triang_num_dims_flag $idim $p4est_triang_domains_limits_flag $domain_limits -wsolution .false. -order $iods -in_space .true.  -check .true. -maxl $ilvs -wmatrix .false. -uconstraints $uconstraints -is_diri $is_diri -is_bconst $is_bconst  $output_handler_dir_path_flag $SCRIPT_NAME $output_handler_prefix_flag $SCRIPT_NAME --dir-path-out $SCRIPT_NAME --prefix $SCRIPT_NAME"
                echo $COMMAND
                eval $COMMAND
                if [ $? -ne 0 ] 
                then
                 final_exit_code=1
                 break 4
                fi
        
              fi
            done
          done
        done
      done
    fi

else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code
