#!/bin/sh
TEST_BINARY_PATH="$1"
final_exit_code=0
if [ -f "$TEST_BINARY_PATH" ]
then   

    points=100000
    type='scalar'

    for op in '+' '/' '*' '^'
    do
      for ops in 2 3
      do
        echo "$TEST_BINARY_PATH --TEST_FUNCTION_NAME test_scalar --TEST_FUNCTION_TYPE $type --TEST_NUM_POINTS $points --TEST_NUM_OPERATORS $ops --TEST_OPERATOR $op"
        $TEST_BINARY_PATH --TEST_FUNCTION_NAME test_scalar --TEST_FUNCTION_TYPE $type --TEST_NUM_POINTS $points --TEST_NUM_OPERATORS $ops --TEST_OPERATOR "$op"
        if [ $? -ne 0 ] 
        then
          final_exit_code=1
        fi
      done
    done

    for type in 'vector' 'tensor'
    do
      for ops in 2 3
      do
        echo "$TEST_BINARY_PATH --TEST_FUNCTION_NAME test_$type --TEST_FUNCTION_TYPE $type --TEST_NUM_POINTS $points --TEST_NUM_OPERATORS $ops"
        $TEST_BINARY_PATH --TEST_FUNCTION_NAME test_$type --TEST_FUNCTION_TYPE $type --TEST_NUM_POINTS $points --TEST_NUM_OPERATORS $ops 
        if [ $? -ne 0 ] 
          then
          final_exit_code=1
        fi
      done
    done
else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
exit $final_exit_code 
