#!/bin/sh
TEST_BINARY_PATH="$1"
TEST_INPUT_DATA_PATH="$2"
final_exit_code=0
if [ -f "$TEST_BINARY_PATH" ]
then
# if [ -d "$TEST_INPUT_DATA_PATH" ] 
#   then
      ###############################################################################################################################
      # Scalar-valued tests
      ###############################################################################################################################


      # Cube + Hexas + Hybrid Void/Full FEs (popcorn pattern)
      for gorder in 1
      do
       for order in 2 3 4 5 6 7 8 
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH -tt structured -dim 2  -order 2 -wsolution .true."
            $TEST_BINARY_PATH -tt structured -dim 2  -order 2 -wsolution .true.
            if [ $? -ne 0 ] 
            then
             final_exit_code=1
            fi
          fi
        done
      done

 #  else
 #     echo "$0: input data directory not found!"
 #     final_exit_code=1
 #  fi
else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code
