#!/bin/sh
TEST_BINARY_PATH="$1"
TEST_INPUT_DATA_PATH="$2"
TEST_SCRIPTS_PATH="$3"
final_exit_code=0

# Load FEMPAR CLAs
. $TEST_SCRIPTS_PATH/fempar_parameters

if [ -f "$TEST_BINARY_PATH" ]
then
  if [ -d "$TEST_INPUT_DATA_PATH" ] 
  then
      ###############################################################################################################################
      # Scalar-valued tests
      ###############################################################################################################################

    # Square + Quads    
    if [ $final_exit_code -eq 0 ] 
    then    
      for gorder in 1
      do
       for order in 2
        do
          for constr in .true. .false.
          do
            if [ $order -ge $gorder ]
            then
              cmd="$TEST_BINARY_PATH $triang_generate_flag 1 $struct_hex_triang_num_dims_flag 2 $struct_hex_triang_num_cells_dir_flag 4 4 0 -in_space .true. -order $order -gorder $gorder -uconstraints $constr"
              echo $cmd
              $cmd
              if [ $? -ne 0 ] 
              then
               final_exit_code=1
               break 3
              fi
            fi
          done
        done
      done
    fi

    # Cube + Hexas  
    if [ $final_exit_code -eq 0 ] 
    then     
      for gorder in 1
      do
       for order in 1
        do
          for constr in .true. .false.
          do
            if [ $order -ge $gorder ]
            then
              cmd="$TEST_BINARY_PATH  $triang_generate_flag 1 $struct_hex_triang_num_dims_flag 3 $struct_hex_triang_num_cells_dir_flag 4 4 4 -in_space .true. -order $order -gorder $gorder -uconstraints $constr"
              echo $cmd
              $cmd
              if [ $? -ne 0 ]
              then
               final_exit_code=1
               break 3
              fi
            fi
          done
        done
      done
    fi

    # Square + Tets        
    if [ $final_exit_code -eq 0 ] 
    then
      for gorder in 1
      do
       for order in 1 
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH $triang_generate_flag 0 $dir_path_flag $TEST_INPUT_DATA_PATH/square_tetrahedra_3x3.gid $prefix_flag square_tetrahedra_3x3 $struct_hex_triang_num_dims_flag 2 -in_space .true. -order $order -gorder $gorder"
            $TEST_BINARY_PATH $triang_generate_flag 0 $dir_path_flag $TEST_INPUT_DATA_PATH/square_tetrahedra_3x3.gid $prefix_flag square_tetrahedra_3x3 $struct_hex_triang_num_dims_flag 2 -in_space .true. -order $order -gorder $gorder 
            if [ $? -ne 0 ] 
            then
             final_exit_code=1
             break 2
            fi
          fi
        done
      done
    fi

    # Cube + Tets
    if [ $final_exit_code -eq 0 ] 
    then      
      for gorder in 1
      do
       for order in 1
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH $triang_generate_flag 0 $dir_path_flag $TEST_INPUT_DATA_PATH/cube_tetrahedra_3x3.gid $prefix_flag cube_tetrahedra_3x3 $struct_hex_triang_num_dims_flag 3 -in_space .true. -order $order -gorder $gorder"
            $TEST_BINARY_PATH $triang_generate_flag 0 $dir_path_flag $TEST_INPUT_DATA_PATH/cube_tetrahedra_3x3.gid $prefix_flag cube_tetrahedra_3x3 $struct_hex_triang_num_dims_flag 3 -in_space .true. -order $order -gorder $gorder
            if [ $? -ne 0 ]
            then
             final_exit_code=1
             break 2
            fi
          fi
        done
      done
    fi
      
   if [ $final_exit_code -eq 0 ] 
    then      
      echo "$TEST_BINARY_PATH $triang_generate_flag 0 $dir_path_flag $TEST_INPUT_DATA_PATH/cube_tetrahedra_5x5_centered.gid $prefix_flag cube_tetrahedra_5x5_centered $struct_hex_triang_num_dims_flag 3 -in_space .true. -order $order -gorder $gorder"
      $TEST_BINARY_PATH $triang_generate_flag 0 $dir_path_flag $TEST_INPUT_DATA_PATH/cube_tetrahedra_5x5_centered.gid $prefix_flag cube_tetrahedra_5x5_centered $struct_hex_triang_num_dims_flag 3 -in_space .true. -order $order -gorder $gorder
      if [ $? -ne 0 ]
      then
        final_exit_code=1
      fi
    fi

   else
      echo "$0: input data directory not found!"
      final_exit_code=1
   fi
else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code
