#!/bin/sh
TEST_BINARY_PATH="$1"
TEST_INPUT_DATA_PATH="$2"
final_exit_code=0
if [ -f "$TEST_BINARY_PATH" ]
then
    final_exit_code=0

    # STOKES test
    rm -Rf $PWD/output_test_nsi_iss_oss_stokes.txt
    $TEST_BINARY_PATH analytical -cnv .false. -ne 4 4 -af NSI-LINEAR-STEADY >> $PWD/output_test_nsi_iss_oss_stokes.txt
    if [ $? -ne 0 ] 
    then
        final_exit_code=1
    fi

    # NAVIER-STOKES test
    rm -Rf $PWD/output_test_nsi_iss_oss_navierstokes.txt
    for number_elements in 2 4 8
    do
	$TEST_BINARY_PATH analytical -cnv .true. -ne $number_elements $number_elements -af NSI-LINEAR-STEADY >> $PWD/output_test_nsi_iss_oss_navierstokes.txt
        if [ $? -ne 0 ] 
        then
          final_exit_code=1
        fi
    done

    if [ $final_exit_code -eq 0 ]
    then 
      # Python script
      aux=$(python $TEST_INPUT_DATA_PATH/test_nsi_iss_oss.py)
      echo $aux
      final_exit_code=$( echo -n $aux | tail -c 1 )
    fi
else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code 
