#!/bin/sh
TEST_BINARY_PATH="$1"
TEST_INPUT_DATA_PATH="$2"
final_exit_code=0
if [ -f "$TEST_BINARY_PATH" ]
then
 if [ -d "$TEST_INPUT_DATA_PATH" ] 
   then
      # Square + Quads       
      for gorder in 1
      do
       for order in 1 2 3
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH -tt structured -nx 2 -ny 2 -order $order -gorder $gorder"
            $TEST_BINARY_PATH -tt structured -nx 2 -ny 2 -order $order -gorder $gorder 
            if [ $? -ne 0 ] 
            then
             final_exit_code=1
            fi
          fi
        done
      done

      # Cube + Hexas         
      for gorder in 1
      do
       for order in 1 2 3
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH -tt structured -dim 3 -nx 2 -ny 2 -nz 2 -order $order -gorder $gorder"
            $TEST_BINARY_PATH -tt structured -dim 3 -nx 2 -ny 2 -nz 2 -order $order -gorder $gorder 
            if [ $? -ne 0 ] 
            then
             final_exit_code=1
            fi
          fi
        done
      done

      # Square +  Tetrahedra       
      for gorder in 1
      do
       for order in 1 2 3
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH -tt unstructured -dim 2 --dir-path $TEST_INPUT_DATA_PATH/square_tetrahedra.gid --prefix square_tetrahedra -order $order -gorder $gorder"
            $TEST_BINARY_PATH -tt unstructured -dim 2 --dir-path $TEST_INPUT_DATA_PATH/square_tetrahedra.gid --prefix square_tetrahedra -order $order -gorder $gorder 
            if [ $? -ne 0 ]
            then
             final_exit_code=1
            fi
          fi
        done
      done

      # Cube + Tetrahedra
      for gorder in 1
      do
        for order in 1 2 3
        do
          if [ $order -ge $gorder ]
          then
            echo "$TEST_BINARY_PATH -tt unstructured -dim 3 --dir-path $TEST_INPUT_DATA_PATH/cube_tetrahedra.gid/ --prefix cube_tetrahedra -order $order -gorder $gorder"
            $TEST_BINARY_PATH -tt unstructured -dim 3 --dir-path $TEST_INPUT_DATA_PATH/cube_tetrahedra.gid/ --prefix cube_tetrahedra -order $order -gorder $gorder
            if [ $? -ne 0 ]
            then
             final_exit_code=1
            fi
          fi
        done
      done

   else
      echo "$0: input data directory not found!"
      final_exit_code=1
   fi
else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
rm -Rf $TEST_INPUT_FILE
exit $final_exit_code
