#!/bin/sh
TEST_BINARY_PATH="$1"
final_exit_code=0
if [ -f "$TEST_BINARY_PATH" ]
then   
      $TEST_BINARY_PATH --STRUCT_HEX_TRIANG_NUM_CELLS_DIM 10 10 10 --FES_REF_FE_ORDERS 3
      if [ $? -ne 0 ] 
      then
         final_exit_code=1
      fi
else
  echo "$0: BINARY not found! Value PROVIDED: $1."
  final_exit_code=1
fi
exit $final_exit_code 
