! Copyright (C) 2014 Santiago Badia, Alberto F. Martín and Javier Principe
!
! This file is part of FEMPAR (Finite Element Multiphysics PARallel library)
!
! FEMPAR is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! FEMPAR is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with FEMPAR. If not, see <http://www.gnu.org/licenses/>.
!
! Additional permission under GNU GPL version 3 section 7
!
! If you modify this Program, or any covered work, by linking or combining it 
! with the Intel Math Kernel Library and/or the Watson Sparse Matrix Package 
! and/or the HSL Mathematical Software Library (or a modified version of them), 
! containing parts covered by the terms of their respective licenses, the
! licensors of this Program grant you additional permission to convey the 
! resulting work. 
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
module triangulation_parameters_names
  use types_names
  implicit none
  
  ! Parameters to define vef_type. Observe that
  ! mod(vef_type,10)     = dimension
  ! mod(vef_type/10,10)  = interior (0) or boundary (1)
  ! vef_type/100         = local (0), interface(1) or ghost(2)
  integer(ip), parameter :: local_interior_dim0 =  0
  integer(ip), parameter :: local_interior_dim1 =  1
  integer(ip), parameter :: local_interior_dim2 =  2
  integer(ip), parameter :: local_boundary_dim0 = 10
  integer(ip), parameter :: local_boundary_dim1 = 11
  integer(ip), parameter :: local_boundary_dim2 = 12

  integer(ip), parameter :: interface_interior_dim0 = 100
  integer(ip), parameter :: interface_interior_dim1 = 101
  integer(ip), parameter :: interface_interior_dim2 = 102
  integer(ip), parameter :: interface_boundary_dim0 = 110
  integer(ip), parameter :: interface_boundary_dim1 = 111
  integer(ip), parameter :: interface_boundary_dim2 = 112

  integer(ip), parameter :: ghost_dim0 = 200
  integer(ip), parameter :: ghost_dim1 = 201
  integer(ip), parameter :: ghost_dim2 = 202
  
  character(len=*), parameter :: static_triang_generate_from_mesh_data_files           = "MESH_DATA_FILES"
  character(len=*), parameter :: static_triang_generate_from_struct_hex_mesh_generator = "STRUCT_HEX_MESH_GENERATOR"
  
  character(len=*), parameter :: static_triang_generate_from_key                      = 'STATIC_TRIANG_GENERATE_FROM'
  character(len=*), parameter :: static_triang_geometric_interpolation_order_key      = 'STATIC_TRIANG_GEOMETRIC_INTERPOLATION_ORDER'
  character(len=*), parameter :: static_triang_geometric_interpolation_order_cla_name = '--'//static_triang_geometric_interpolation_order_key
  character(len=*), parameter :: static_triang_generate_cla_name                      = '--'//static_triang_generate_from_key
  character(len=*), parameter :: static_triang_generate_cla_choices                   = static_triang_generate_from_mesh_data_files // ',' // &
                                                                                        static_triang_generate_from_struct_hex_mesh_generator
                                                                                        
  character(len=*), parameter :: static_triang_generate_cla_help = "Approach to generate static triangulation" // BRK_LINE // & 
                                     BULLET_FLAP_HELP_MESSAGE // static_triang_generate_from_mesh_data_files // ": Static triangulation is generated by importing mesh data files from file system" // &
                                                                 " typically generated by an external unstructured mesh generator (e.g., GiD)" // BRK_LINE // &
                                     BULLET_FLAP_HELP_MESSAGE // static_triang_generate_from_struct_hex_mesh_generator // ": Static triangulation is directly generated in" // & 
                                                                 " memory by means of a uniform/structured hexaedral mesh generator"

  character(len=*), parameter :: static_triang_geometric_interpolation_order_cla_help = 'Interpolation order static triangulation geometrical mapping' // BRK_LINE // &
                                                                                        '(only partial/unstable support for order>1)'
                                                                               
  character(len=*), parameter :: triang_identify_disconn_components_key = 'TRIANG_IDENTIFY_DISCONNECTED_COMPONENTS'
  character(len=*), parameter :: triang_identify_disconn_components_cla_name = '--'// triang_identify_disconn_components_key
  character(len=*), parameter :: triang_identify_disconn_components_cla_help = 'Activate/deactivate set up of a cell-wise data array within triangulation. In this array, ' // BRK_LINE // &
                                                                                   'referred to as disconnected_cells_set_id, cells that belong to the same disconnected component' // BRK_LINE // & 
                                                                                   'are labelled with the same ID, starting from 0. If deactivated, all cells are labelled with ID 0.'

  character(len=*), parameter :: vertex_coupling = 'VERTEX_COUPLING' 
  character(len=*), parameter :: face_coupling   = 'FACE_COUPLING' 
  character(len=*), parameter :: triang_identify_disconn_components_dgraph_coupling_key = 'TRIANG_IDENTIFY_DISCONNECTED_COMPONENTS_DGRAPH_COUPLING'
  character(len=*), parameter :: triang_identify_disconn_components_dgraph_coupling_cla_name = '--'// triang_identify_disconn_components_dgraph_coupling_key
  character(len=*), parameter :: triang_identify_disconn_components_dgraph_coupling_cla_help = 'Criterion to decide cell neighbors in the dual graph built by triangulation' // BRK_LINE // &
                        BULLET_FLAP_HELP_MESSAGE // vertex_coupling // ": cells are neighbors if they share at least one vertex" // BRK_LINE // &
                        BULLET_FLAP_HELP_MESSAGE // face_coupling // ": cells are neighbors if they share a face"
  character(len=*), parameter :: triang_identify_disconn_components_dgraph_coupling_cla_choices = vertex_coupling // ',' // face_coupling

  
  integer(ip), parameter :: refinement = 1 
  integer(ip), parameter :: coarsening = -1 
  integer(ip), parameter :: do_nothing = 0   
  integer(ip), parameter :: default_static_triang_geometric_interpolation_order = 1
  
end module triangulation_parameters_names
