! Copyright (C) 2014 Santiago Badia, Alberto F. Martín and Javier Principe
!
! This file is part of FEMPAR (Finite Element Multiphysics PARallel library)
!
! FEMPAR is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! FEMPAR is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with FEMPAR. If not, see <http://www.gnu.org/licenses/>.
!
! Additional permission under GNU GPL version 3 section 7
!
! If you modify this Program, or any covered work, by linking or combining it 
! with the Intel Math Kernel Library and/or the Watson Sparse Matrix Package 
! and/or the HSL Mathematical Software Library (or a modified version of them), 
! containing parts covered by the terms of their respective licenses, the
! licensors of this Program grant you additional permission to convey the 
! resulting work. 
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
module reference_fe_names
  use allocatable_array_ip1_names
  use allocatable_array_ip2_names
  use field_names
  use types_names
  use list_types_names
  use memor_names
  implicit none
# include "debug.i90"

  private

  ! This module includes all the reference FE related machinery that is required
  ! to integrate FE schemes. It includes the following types:
  !
  ! * reference_fe_t: the basic reference_fe object, which is an abstract type
  ! * quad_lagrangian_reference_fe_t: one particular concrete version of the 
  !   reference fe_t
  ! * quadrature_t: Set of points and weights to perform numerical integration.
  !   It is created by the concrete reference_fe_t by providing the maximum order
  !   to be integrated exactly for zero order terms, e.g., mass matrix
  ! * interpolation_t: The value of the reference FE shape functions (first and second
  !   order derivatives) on the quadrature points. It is generated by a concrete 
  !   reference_fe_t and a quadrature_t. It is computed in the concrete reference_fe_t
  ! * fe_map_t: It provides the mapping from a physical FE to the reference FE
  !   (jacobian, etc.)
  ! * volume_integrator_t: It aggregates all the aforementioned structures to be
  !   used in the FE element integration subroutine. In particular, one 
  !   reference_fe_t for the unknowns and one for the geometry (for non-isoparametric
  !   cases), one quadrature, and the corresponding interpolation. Further, it 
  !   includes the physical FE to the reference one in a fe_map_t and the
  !   composition of the FE map and the interpolation, to provide derivatives in the
  !   physical space

  type quadrature_t
     private
     integer(ip)           ::   &
          number_dimensions,    &
          number_quadrature_points
     real(rp), allocatable :: &
          coordinates(:,:),   &   
          weight(:)                         
   contains
     procedure, non_overridable :: create => quadrature_create
     procedure, non_overridable :: free   => quadrature_free
     procedure, non_overridable :: print  => quadrature_print
     procedure, non_overridable :: get_number_dimensions => quadrature_get_number_dimensions
     procedure, non_overridable :: get_number_quadrature_points => quadrature_get_number_quadrature_points
     procedure, non_overridable :: get_weight => quadrature_get_weight
  end type quadrature_t

  type p_quadrature_t
     type(quadrature_t), pointer :: p => NULL()
   contains
     procedure :: allocate => p_quadrature_allocate
     procedure :: free     => p_quadrature_free
  end type p_quadrature_t

  ! Types
  public :: quadrature_t, p_quadrature_t

  !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  type interpolation_t
     private
     integer(ip)                ::  &
          number_dimensions,        &      
          number_shape_functions,   &      
          number_quadrature_points, &      
          number_entries_symmetric_tensor
     real(rp), allocatable      ::  &
          shape_functions(:,:),     &   
          shape_derivatives(:,:,:), &   
          hessian(:,:,:)     
   contains
     procedure, non_overridable :: create => interpolation_create
     procedure, non_overridable :: free   => interpolation_free
     procedure, non_overridable :: copy   => interpolation_copy
     procedure, non_overridable :: print  => interpolation_print
     !procedure, non_overridable :: get_number_dimensions => interpolation_get_number_dimensions
     !procedure, non_overridable :: get_number_shape_functions => interpolation_get_number_shape_functions
     !procedure, non_overridable :: get_number_evaluation_points => interpolation_get_number_evaluation_points
     !procedure, non_overridable :: get_number_entries_symmetric_tensor => interpolation_get_number_entries_symmetric_tensor
     !procedure, non_overridable :: get_shape_function => interpolation_get_shape_function
     !procedure, non_overridable :: get_shape_derivative => interpolation_get_shape_derivative
     !procedure, non_overridable :: get_hessian  => interpolation_get_hessian
  end type interpolation_t

  public :: interpolation_t
  
  !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
  type interpolation_face_restriction_t
     private
     integer(ip)                           :: number_shape_functions
     integer(ip)                           :: number_quadrature_points
     integer(ip)                           :: number_faces
     integer(ip)                           :: active_face_id
     type(interpolation_t), allocatable :: interpolation(:)
     type(interpolation_t)              :: interpolation_o_map
   contains
     procedure, non_overridable :: create => interpolation_face_restriction_create
     procedure, non_overridable :: free   => interpolation_face_restriction_free
  end type interpolation_face_restriction_t

  public :: interpolation_face_restriction_t

 !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  type fe_map_t
     private
     ! Map's Jacobian (number_dimensions,number_dimensions,number_quadrature_points)
     real(rp), allocatable    :: jacobian(:,:,:)    
     ! Map's Jacobian inverse (number_dimensions,number_dimensions,number_quadrature_points)       
     real(rp), allocatable    :: inv_jacobian(:,:,:)     
     ! Map's Jacobian det (number_quadrature_points)  
     real(rp), allocatable    :: det_jacobian(:)  
     ! Map's 2nd derivatives (number_dime,number_dime,number_dime,number_quadrature_points)         
     real(rp), allocatable    :: d2sdx(:,:,:,:)     
     ! Coordinates of git  points (number_dimensions,number_quadrature_points)       
     type(point_t), allocatable    :: coordinates_quadrature(:)  
     ! Coordinates of evaluation points (number_dimensions,number_corners of element/face)  
     type(point_t), allocatable    :: coordinates_vertices(:)  
     ! Vector normals outside the face (only allocated when using fe_map to integrate on faces) 
     real(rp), allocatable    :: normals(:,:)  
     ! Geometry interpolation_t in the reference element domain    
     type(interpolation_t) :: interpolation_geometry   
     ! Characteristic length of the reference element
     real(rp)                 :: reference_fe_characteristic_length
     ! Number of dimensions
     integer(ip)              :: number_dimensions
     ! Number of quadrature points
     integer(ip)              :: number_quadrature_points
   contains
     procedure, non_overridable :: create                         => fe_map_create
     procedure, non_overridable :: create_on_face                 => fe_map_create_on_face
     procedure, non_overridable :: fe_map_face_map_create         => fe_map_face_map_create
     procedure, non_overridable :: update                         => fe_map_update
     procedure, non_overridable :: face_map_update                => fe_map_face_map_update
     procedure, non_overridable :: free                           => fe_map_free
     procedure, non_overridable :: print                          => fe_map_print
     procedure, non_overridable :: get_det_jacobian               => fe_map_get_det_jacobian
     procedure, non_overridable :: compute_h                      => fe_map_compute_h
     procedure, non_overridable :: compute_h_min                  => fe_map_compute_h_min
     procedure, non_overridable :: compute_h_max                  => fe_map_compute_h_max
     procedure, non_overridable :: get_coordinates                => fe_map_get_coordinates
     procedure, non_overridable :: get_inv_jacobian_tensor        => fe_map_get_inv_jacobian_tensor
     procedure, non_overridable :: get_reference_h                => fe_map_get_reference_h
     procedure, non_overridable :: apply_inv_jacobian             => fe_map_apply_inv_jacobian
     procedure, non_overridable :: compute_quadrature_coordinates => fe_map_compute_quadrature_coordinates
     procedure, non_overridable :: get_quadrature_coordinates     => fe_map_get_quadrature_coordinates
  end type fe_map_t

  type p_fe_map_t
     class(fe_map_t), pointer :: p => NULL()   
   contains
     procedure :: allocate => p_fe_map_allocate
     procedure :: free     => p_fe_map_free
  end type p_fe_map_t

  public :: fe_map_t, p_fe_map_t
  
  !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
  type fe_map_face_restriction_t
     private
     integer(ip)                 :: number_faces = 0
     integer(ip)                 :: active_face_id
     type(fe_map_t), allocatable :: fe_map(:)
   contains
     procedure, non_overridable :: create => fe_map_face_restriction_create
     procedure, non_overridable :: update => fe_map_face_restriction_update
     procedure, non_overridable :: free   => fe_map_face_restriction_free
     procedure, non_overridable :: get_coordinates => fe_map_face_restriction_get_coordinates
  end type fe_map_face_restriction_t

  !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  character(*), parameter :: field_type_scalar           = 'scalar'
  character(*), parameter :: field_type_vector           = 'vector'
  character(*), parameter :: field_type_tensor           = 'tensor'
  character(*), parameter :: field_type_symmetric_tensor = 'symmetric_tensor'
  
  character(*), parameter :: topology_quad = "quad"
  character(*), parameter :: topology_tet  = "tet"
  character(*), parameter :: fe_type_lagrangian = "Lagrangian"
  
  ! Abstract reference_fe
  type, abstract ::  reference_fe_t
     private
     character(:), allocatable :: &
          topology,               &    ! topology of element, 'tet', 'quad', 'prism', ...
          fe_type,                &    ! 'Lagrangian', 'RT', ...
          field_type                   ! 'scalar', 'vector', 'tensor', 'symmetric_tensor'

     integer(ip)              ::    &        
          number_dimensions,        &
          order,                    &
          number_field_components

     logical                  ::    &
          continuity,               &      ! CG(.true.)/DG(.false.)
          conformity                       ! .true. for discontinuous L2 conforming spaces 
                                           ! that do not require to enforce weakly continuity

     integer(ip)              ::    &
          number_vefs,              &        
          number_nodes,             &        
          number_vefs_dimension(5)

     type(allocatable_array_ip1_t)  :: orientation        ! orientation of the vefs 
     type(list_t)                   :: interior_nodes_vef ! interior nodes per vef
     type(list_t)                   :: nodes_vef          ! all nodes per vef
     type(list_t)                   :: vertices_vef       ! vertices per vef
     type(list_t)                   :: vefs_vef           ! all vefs per vef
     type(list_t)                   :: own_nodes_vef
     type(list_t)                   :: face_integration_coupling_nodes_face
     type(quadrature_t)             :: nodal_quadrature

     

     integer(ip), allocatable :: number_rotations_per_dimension(:)
     integer(ip), allocatable :: number_orientations_per_dimension(:)
     type(allocatable_array_ip2_t), allocatable :: own_node_permutations(:)
   contains
     ! TBPs
     ! Fill topology, fe_type, number_dimensions, order, continuity 
     procedure(create_interface)                        , deferred :: create 
     ! TBP to create a quadrature for a reference_fe_t
     procedure(create_quadrature_interface)             , deferred :: create_quadrature
     !procedure(create_quadrature_on_faces_interface)    , deferred :: create_quadrature_on_faces
     procedure(create_face_quadrature_interface)        , deferred :: create_face_quadrature
     ! TBP to create an interpolation from a quadrature_t and reference_fe_t, 
     ! i.e., the value of the shape functions of the reference element on the quadrature points. 
     procedure(create_interpolation_interface)          , deferred :: create_interpolation 
     procedure(create_face_interpolation_interface)     , deferred :: create_face_interpolation
     procedure(create_face_local_interpolation_interface),deferred :: create_face_local_interpolation
     procedure(update_interpolation_interface)          , deferred :: update_interpolation
     procedure(update_interpolation_face_interface)     , deferred :: update_interpolation_face
     procedure(get_component_node_interface)            , deferred :: get_component_node
     procedure(get_scalar_from_vector_node_interface)   , deferred :: get_scalar_from_vector_node
     procedure (get_number_nodes_scalar_interface),       deferred :: get_number_nodes_scalar
     
     procedure(get_value_scalar_interface)           , deferred :: get_value_scalar
     procedure(get_value_vector_interface)           , deferred :: get_value_vector
     !procedure(get_value_tensor_interface)          , deferred :: get_value_tensor           ! Pending
     !procedure(get_value_symmetric_tensor_interface), deferred :: get_value_symmetric_tensor ! Pending
     generic :: get_value => get_value_scalar,get_value_vector!                                      &
!          &                !,get_value_tensor,get_value_symmetric_tensor
    
     procedure(get_gradient_scalar_interface)          , deferred :: get_gradient_scalar
     procedure(get_gradient_vector_interface)          , deferred :: get_gradient_vector
     !procedure(get_gradient_tensor_interface)          , deferred :: get_gradient_tensor ! Pending
     generic :: get_gradient => get_gradient_scalar,get_gradient_vector!                             &
!          &                   !,get_value_tensor,get_value_symmetric_tensor
                                                                                     
     !procedure(get_symmetric_gradient_vector_interface), deferred :: get_symmetric_gradient_vector ! Pending
     !generic :: get_symmetric_gradient => get_symmetric_gradient_scalar

     procedure(get_divergence_vector_interface)        , deferred :: get_divergence_vector ! Pending
   !  procedure(get_divergence_tensor_interface)        , deferred :: get_divergence_tensor ! Pending
     generic :: get_divergence => get_divergence_vector !, get_divergence_tensor
                                                                                     
     procedure(get_curl_vector_interface)              , deferred :: get_curl_vector ! Pending
     generic :: get_curl => get_curl_vector

     procedure(evaluate_fe_function_scalar_interface), deferred :: evaluate_fe_function_scalar
     procedure(evaluate_fe_function_vector_interface), deferred :: evaluate_fe_function_vector
     procedure(evaluate_fe_function_tensor_interface), deferred :: evaluate_fe_function_tensor
     generic :: evaluate_fe_function => evaluate_fe_function_scalar, &
                                      & evaluate_fe_function_vector, &
                                      & evaluate_fe_function_tensor
     
     ! This subroutine gives the reodering (o2n) of the nodes of an vef given an orientation 'o'
     ! and a delay 'r' wrt to a refence element sharing the same vef.
     procedure (check_compatibility_of_vefs_interface), deferred :: &
          &     check_compatibility_of_vefs
     procedure (get_characteristic_length_interface) , deferred :: get_characteristic_length
     procedure (set_nodal_quadrature_interface), deferred :: set_nodal_quadrature          
     procedure (fill_interior_points_permutation_interface), deferred :: fill_interior_points_permutation

     procedure (set_scalar_field_to_nodal_values_interface), deferred :: set_scalar_field_to_nodal_values
     procedure (set_vector_field_to_nodal_values_interface), deferred :: set_vector_field_to_nodal_values
     procedure (set_tensor_field_to_nodal_values_interface), deferred :: set_tensor_field_to_nodal_values
     generic :: set_field_to_nodal_values => set_scalar_field_to_nodal_values, &
                                           & set_vector_field_to_nodal_values, &
                                           & set_tensor_field_to_nodal_values

     procedure (interpolate_nodal_values_interface), deferred :: interpolate_nodal_values

     procedure (get_number_subelements_interface),       deferred :: get_number_subelements
     procedure (get_subelements_connectivity_interface), deferred :: get_subelements_connectivity


     ! generic part of the subroutine above
     procedure :: free  => reference_fe_free
     procedure :: print => reference_fe_print

     ! Set number_dimensions, order, continuity, field_type, number_field_components
     procedure :: set_common_data => reference_fe_set_common_data
     procedure :: set_topology => reference_fe_set_topology
     procedure :: set_fe_type => reference_fe_set_fe_type

     ! Getters
     procedure :: get_topology => reference_fe_get_topology
     procedure :: get_fe_type => reference_fe_get_fe_type
     procedure :: get_field_type => reference_fe_get_field_type
     procedure :: get_number_dimensions => reference_fe_get_number_dimensions
     procedure :: get_order => reference_fe_get_order
     procedure :: get_continuity => reference_fe_get_continuity
     procedure :: get_conformity => reference_fe_get_conformity
     procedure :: get_number_field_components => reference_fe_get_number_field_components
     procedure :: get_number_vefs => reference_fe_get_number_vefs
     procedure :: get_number_vertices => reference_fe_get_number_vertices
     procedure :: get_first_vertex_id => reference_fe_get_first_vertex_id
     procedure :: get_number_vertices_per_edge => reference_fe_get_number_vertices_per_edge
     procedure :: get_number_vertices_per_face => reference_fe_get_number_vertices_per_face
     procedure :: get_number_edges => reference_fe_get_number_edges
     procedure :: get_first_edge_id => reference_fe_get_first_edge_id
     procedure :: get_number_faces => reference_fe_get_number_faces
     procedure :: get_first_face_id => reference_fe_get_first_face_id
     procedure :: get_number_vefs_of_dimension  => reference_fe_get_number_vefs_of_dimension
     procedure :: get_first_vef_id_of_dimension => reference_fe_get_first_vef_id_of_dimension 
     procedure :: get_number_nodes => reference_fe_get_number_nodes
     procedure :: get_vef_dimension  => reference_fe_get_vef_dimension
     procedure :: get_vertices_vef  =>   reference_fe_get_vertices_vef
     procedure :: get_nodes_vef   =>   reference_fe_get_nodes_vef
     procedure :: get_vefs_vef   =>   reference_fe_get_vefs_vef
     procedure :: get_number_vertices_vef => reference_fe_get_number_vertices_vef
     procedure :: get_number_own_nodes_vef => reference_fe_get_number_own_nodes_vef
     procedure :: get_own_node_vef => reference_fe_get_own_node_vef
     procedure :: get_face_integration_coupling_number_nodes_face => reference_fe_get_face_integration_coupling_number_nodes_face
     procedure :: get_face_integration_coupling_node_face => reference_fe_get_face_integration_coupling_node_face
     procedure :: get_orientation => reference_fe_get_orientation     
     procedure :: get_nodal_quadrature => reference_fe_get_nodal_quadrature
     procedure :: compute_relative_orientation => reference_fe_compute_relative_orientation
     procedure :: compute_relative_rotation => reference_fe_compute_relative_rotation
     procedure :: get_permuted_own_node_vef  => reference_fe_get_permuted_own_node_vef
  end type reference_fe_t

  type p_reference_fe_t
    class(reference_fe_t), pointer :: p => NULL()
  contains
    procedure :: free => p_reference_fe_free
  end type p_reference_fe_t

  abstract interface
     subroutine create_interface ( this, number_dimensions, order, field_type, continuity, enable_face_integration )
       import :: reference_fe_t, ip
       implicit none 
       class(reference_fe_t), intent(inout) :: this 
       integer(ip)          , intent(in)    :: number_dimensions
       integer(ip)          , intent(in)    :: order
       character(*)         , intent(in)    :: field_type
       logical             , intent(in)    :: continuity
       logical, optional    , intent(in)    :: enable_face_integration
     end subroutine create_interface
     
     subroutine create_quadrature_interface ( this, quadrature, max_order )
       import :: reference_fe_t, quadrature_t, ip
       implicit none 
       class(reference_fe_t), intent(in)    :: this
       type(quadrature_t), intent(inout) :: quadrature
       integer(ip), optional, intent(in)    :: max_order
     end subroutine create_quadrature_interface
 
     subroutine create_face_quadrature_interface ( this, quadrature, max_order  )
       import :: reference_fe_t, quadrature_t, ip
       implicit none
       class(reference_fe_t), intent(in)    :: this
       type(quadrature_t), intent(inout) :: quadrature
       integer(ip), optional, intent(in)    :: max_order
     end subroutine create_face_quadrature_interface
     
     subroutine create_interpolation_interface ( this, quadrature, interpolation, compute_hessian )
       import :: reference_fe_t, quadrature_t, interpolation_t
       implicit none 
       class(reference_fe_t)   , intent(in)    :: this 
       type(quadrature_t)   , intent(in)    :: quadrature
       type(interpolation_t), intent(inout) :: interpolation
       logical       , optional, intent(in)    :: compute_hessian
     end subroutine create_interpolation_interface

     subroutine create_face_local_interpolation_interface ( this, quadrature, interpolation )
       import :: reference_fe_t, quadrature_t, interpolation_t
       implicit none
       class(reference_fe_t)   , intent(in)    :: this
       type(quadrature_t)   , intent(in)    :: quadrature
       type(interpolation_t), intent(inout) :: interpolation
     end subroutine create_face_local_interpolation_interface

     subroutine create_face_interpolation_interface ( this, local_face_id , local_quadrature,       &
          &                                           face_interpolation)
       import :: reference_fe_t, ip, quadrature_t, interpolation_t
       implicit none 
       class(reference_fe_t)     , intent(in)    :: this
       integer(ip)               , intent(in)    :: local_face_id
       type(quadrature_t)     , intent(in)    :: local_quadrature
       type(interpolation_t)  , intent(inout) :: face_interpolation
     end subroutine create_face_interpolation_interface
 
     function get_component_node_interface( this, node )
       import :: reference_fe_t, ip
       implicit none
       class(reference_fe_t), intent(in) :: this 
       integer(ip), intent(in) :: node
       integer(ip) :: get_component_node_interface
     end function get_component_node_interface
 
     function get_scalar_from_vector_node_interface( this, node )
       import :: reference_fe_t, ip
       implicit none
       class(reference_fe_t), intent(in) :: this 
       integer(ip), intent(in) :: node
       integer(ip) :: get_scalar_from_vector_node_interface
     end function get_scalar_from_vector_node_interface

     function get_number_nodes_scalar_interface(this) result(number_nodes_scalar)
     import :: reference_fe_t, ip
       implicit none
       class(reference_fe_t), intent(in) :: this
       integer(ip)                       :: number_nodes_scalar
     end function get_number_nodes_scalar_interface

     subroutine get_value_scalar_interface( this, actual_cell_interpolation, ishape, qpoint,        &
          &                                 scalar_field )
       import :: reference_fe_t, interpolation_t, ip, rp
       implicit none
       class(reference_fe_t)   , intent(in)  :: this 
       type(interpolation_t), intent(in)  :: actual_cell_interpolation 
       integer(ip)             , intent(in)  :: ishape
       integer(ip)             , intent(in)  :: qpoint
       real(rp)                , intent(out) :: scalar_field
     end subroutine get_value_scalar_interface
     
     subroutine get_value_vector_interface( this, actual_cell_interpolation, ishape, qpoint,        &
          &                                 vector_field )
       import :: reference_fe_t, interpolation_t, vector_field_t, ip
       implicit none
       class(reference_fe_t)   , intent(in)  :: this 
       type(interpolation_t), intent(in)  :: actual_cell_interpolation 
       integer(ip)             , intent(in)  :: ishape
       integer(ip)             , intent(in)  :: qpoint
       type(vector_field_t)    , intent(out) :: vector_field
     end subroutine get_value_vector_interface
     
     subroutine get_gradient_scalar_interface( this, actual_cell_interpolation, ishape, qpoint,     &
          &                                    vector_field )
       import :: reference_fe_t, interpolation_t, vector_field_t, ip
       implicit none
       class(reference_fe_t)   , intent(in)  :: this 
       type(interpolation_t), intent(in)  :: actual_cell_interpolation 
       integer(ip)             , intent(in)  :: ishape
       integer(ip)             , intent(in)  :: qpoint
       type(vector_field_t)    , intent(out) :: vector_field
     end subroutine get_gradient_scalar_interface
     
     subroutine get_gradient_vector_interface( this, actual_cell_interpolation, ishape, qpoint,     &
          &                                    tensor_field )
       import :: reference_fe_t, interpolation_t, tensor_field_t, ip
       implicit none
       class(reference_fe_t)   , intent(in)  :: this 
       type(interpolation_t), intent(in)  :: actual_cell_interpolation 
       integer(ip)             , intent(in)  :: ishape
       integer(ip)             , intent(in)  :: qpoint
       type(tensor_field_t)    , intent(out) :: tensor_field
     end subroutine get_gradient_vector_interface

     subroutine get_divergence_vector_interface( this, actual_cell_interpolation, ishape, qpoint,        &
          &                                 scalar_field )
      import :: reference_fe_t, interpolation_t, ip, rp
       implicit none
       class(reference_fe_t)   , intent(in)  :: this 
       type(interpolation_t), intent(in)  :: actual_cell_interpolation 
       integer(ip)             , intent(in)  :: ishape
       integer(ip)             , intent(in)  :: qpoint
       real(rp)                , intent(out) :: scalar_field
     end subroutine get_divergence_vector_interface

     subroutine get_curl_vector_interface( this, actual_cell_interpolation, ishape, qpoint,     &
          &                                    vector_field )
       import :: reference_fe_t, interpolation_t, vector_field_t, ip
       implicit none
       class(reference_fe_t)   , intent(in)  :: this 
       type(interpolation_t), intent(in)  :: actual_cell_interpolation 
       integer(ip)             , intent(in)  :: ishape
       integer(ip)             , intent(in)  :: qpoint
       type(vector_field_t)    , intent(out) :: vector_field
     end subroutine get_curl_vector_interface

     subroutine evaluate_fe_function_scalar_interface( this, &
                                                     & actual_cell_interpolation, &
                                                     & nodal_values, &
                                                     & quadrature_points_values)
       import :: reference_fe_t, interpolation_t, rp
       implicit none
       class(reference_fe_t)   , intent(in)    :: this 
       type(interpolation_t), intent(in)    :: actual_cell_interpolation 
       real(rp)                , intent(in)    :: nodal_values(:)
       real(rp)                , intent(inout) :: quadrature_points_values(:)
     end subroutine evaluate_fe_function_scalar_interface

     subroutine evaluate_fe_function_vector_interface( this, &
                                                     & actual_cell_interpolation, &
                                                     & nodal_values, &
                                                     & quadrature_points_values)
       import :: reference_fe_t, interpolation_t, rp, vector_field_t
       implicit none
       class(reference_fe_t)   , intent(in)    :: this 
       type(interpolation_t), intent(in)    :: actual_cell_interpolation 
       real(rp)                , intent(in)    :: nodal_values(:)
       type(vector_field_t)    , intent(inout) :: quadrature_points_values(:)
     end subroutine evaluate_fe_function_vector_interface

     subroutine evaluate_fe_function_tensor_interface( this, &
                                                     & actual_cell_interpolation, &
                                                     & nodal_values, &
                                                     & quadrature_points_values)
       import :: reference_fe_t, interpolation_t, rp, tensor_field_t
       implicit none
       class(reference_fe_t)   , intent(in)    :: this 
       type(interpolation_t), intent(in)    :: actual_cell_interpolation 
       real(rp)                , intent(in)    :: nodal_values(:)
       type(tensor_field_t)    , intent(inout) :: quadrature_points_values(:)
     end subroutine evaluate_fe_function_tensor_interface     
     
     function check_compatibility_of_vefs_interface(target_reference_fe, &
          &                       source_reference_fe, source_vef_id,target_vef_id)
       import :: reference_fe_t, ip
       implicit none
       class(reference_fe_t), intent(in) :: target_reference_fe
       class(reference_fe_t), intent(in)  :: source_reference_fe
       integer(ip)          , intent(in)  :: source_vef_id
       integer(ip)          , intent(in)  :: target_vef_id 
       logical :: check_compatibility_of_vefs_interface
     end function  check_compatibility_of_vefs_interface

     function get_characteristic_length_interface( this)
       import :: reference_fe_t, rp
       implicit none 
       class(reference_fe_t), intent(in) :: this 
       real(rp)  :: get_characteristic_length_interface 
     end function get_characteristic_length_interface

     subroutine update_interpolation_interface ( this, fe_map, interpolation_reference_cell,        &
          &                            interpolation_real_cell )
       import :: reference_fe_t, fe_map_t, interpolation_t
       implicit none 
       class(reference_fe_t)    , intent(in)    :: this 
       type(fe_map_t)           , intent(in)    :: fe_map
       type(interpolation_t) , intent(in)    :: interpolation_reference_cell
       type(interpolation_t) , intent(inout) :: interpolation_real_cell
     end subroutine update_interpolation_interface

     subroutine update_interpolation_face_interface ( this, local_face_id,fe_map_face_restriction,  &
          &                                           interpolation_face_restriction)
       import :: reference_fe_t, ip, fe_map_face_restriction_t,  interpolation_face_restriction_t
       implicit none 
       class(reference_fe_t)                 , intent(in)    :: this 
       integer(ip)                           , intent(in)    :: local_face_id
       type(fe_map_face_restriction_t)       , intent(in)    :: fe_map_face_restriction
       type(interpolation_face_restriction_t), intent(inout) :: interpolation_face_restriction
     end subroutine update_interpolation_face_interface

     subroutine set_nodal_quadrature_interface ( this )
       import :: reference_fe_t
       implicit none
       class(reference_fe_t), intent(inout) :: this 
     end subroutine set_nodal_quadrature_interface

     subroutine set_scalar_field_to_nodal_values_interface ( this, code, values, nodal_codes, &
          &                                                  nodal_values, unknown_component)
       import :: reference_fe_t, rp, ip
       implicit none
       class(reference_fe_t), intent(in)    :: this 
       integer(ip)          , intent(in)    :: code
       real(rp)             , intent(in)    :: values(:)
       integer(ip)          , intent(in)    :: nodal_codes(:)
       real(rp)             , intent(inout) :: nodal_values(:)
       integer(ip), optional, intent(in)    :: unknown_component
     end subroutine set_scalar_field_to_nodal_values_interface

     subroutine set_vector_field_to_nodal_values_interface ( this, code, values, nodal_codes, &
          &                                                  nodal_values)
       import :: reference_fe_t, vector_field_t, ip, rp
       implicit none
       class(reference_fe_t), intent(in)    :: this
       integer(ip)          , intent(in)    :: code
       type(vector_field_t) , intent(in)    :: values(:)
       integer(ip)          , intent(in)    :: nodal_codes(:)
       real(rp)             , intent(inout) :: nodal_values(:)
     end subroutine set_vector_field_to_nodal_values_interface

     subroutine set_tensor_field_to_nodal_values_interface ( this, code, values, nodal_codes, &
          &                                                  nodal_values)
       import :: reference_fe_t, tensor_field_t, ip, rp
       implicit none
       class(reference_fe_t), intent(in)    :: this 
       integer(ip)          , intent(in)    :: code
       type(tensor_field_t) , intent(in)    :: values(:)
       integer(ip)          , intent(in)    :: nodal_codes(:)
       real(rp)             , intent(inout) :: nodal_values(:)
     end subroutine set_tensor_field_to_nodal_values_interface
               
     subroutine fill_interior_points_permutation_interface( this,&
                                                            dimension,&
                                                            number_interior_points,&
                                                            interior_points_permutation )
       import :: reference_fe_t, ip
       implicit none 
       class(reference_fe_t)                 , intent(inout) :: this 
       integer(ip)                           , intent(in)    :: dimension
       integer(ip)                           , intent(in)    :: number_interior_points
       integer(ip)      , allocatable        , intent(inout) :: interior_points_permutation(:,:)
     end subroutine fill_interior_points_permutation_interface

     subroutine interpolate_nodal_values_interface(this,nodal_interpolation,nodal_values_origin, &
          &                                        nodal_values_destination)
       import :: reference_fe_t, interpolation_t, rp
       implicit none 
       class(reference_fe_t), intent(in)    :: this 
       type(interpolation_t), intent(in)    :: nodal_interpolation
       real(rp)             , intent(in)    :: nodal_values_origin(:)
       real(rp)             , intent(inout) :: nodal_values_destination(:)
     end subroutine interpolate_nodal_values_interface
     
     function get_number_subelements_interface(this) result(number_subelements)
     import :: reference_fe_t, ip
       implicit none
       class(reference_fe_t), intent(in)    :: this
       integer(ip)                          :: number_subelements
     end function get_number_subelements_interface

     subroutine get_subelements_connectivity_interface(this, connectivity)
     import :: reference_fe_t, ip
       implicit none
       class(reference_fe_t), intent(in)    :: this
       integer(ip),           intent(inout) :: connectivity(:,:)
     end subroutine get_subelements_connectivity_interface
  end interface

  public :: reference_fe_t, p_reference_fe_t
  public :: field_type_scalar, field_type_vector, field_type_tensor, field_type_symmetric_tensor
  public :: topology_quad, topology_tet, fe_type_lagrangian
  
  !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  type, abstract, extends(reference_fe_t) :: lagrangian_reference_fe_t
     private
     integer(ip)              :: number_nodes_scalar
     integer(ip), allocatable :: node_component_array(:,:)
     integer(ip), allocatable :: node_array_component(:,:)
   contains
     ! Additional deferred methods
     procedure (fill_scalar_interface)                     , deferred :: fill_scalar
     procedure (fill_quadrature_interface)                 , deferred :: fill_quadrature
     procedure (fill_nodal_quadrature_interface)           , deferred :: fill_nodal_quadrature     
     procedure (fill_interpolation_interface)              , deferred :: fill_interpolation
     procedure (fill_face_interpolation_interface)         , deferred :: fill_face_interpolation
     procedure (get_number_interior_points_x_dim_interface), deferred :: get_number_interior_points_x_dim
     procedure (local_coordinates_to_local_id_interface)   , deferred :: local_coordinates_to_local_id
     procedure (local_id_to_local_coordinates_interface)   , deferred :: local_id_to_local_coordinates
     procedure (set_coordinates_1D_interface)              , deferred :: set_coordinates_1D
     procedure (set_permutation_2D_interface)              , deferred :: set_permutation_2D
     procedure (set_number_quadrature_points_interface)    , deferred :: set_number_quadrature_points
     procedure (compute_number_nodes_scalar_interface)     , deferred :: compute_number_nodes_scalar
     ! Deferred TBP implementors
     procedure :: create                           => lagrangian_reference_fe_create
     procedure :: fill_interior_points_permutation => lagrangian_reference_fe_fill_interior_points_permutation
     procedure :: create_quadrature                => lagrangian_reference_fe_create_quadrature
     procedure :: create_face_quadrature           => lagrangian_reference_fe_create_face_quadrature
     procedure :: create_interpolation             => lagrangian_reference_fe_create_interpolation
     procedure :: create_face_interpolation        => lagrangian_reference_fe_create_face_interpolation
     procedure :: create_face_local_interpolation  => lagrangian_reference_fe_create_face_local_interpolation
     procedure :: update_interpolation             => lagrangian_reference_fe_update_interpolation
     procedure :: update_interpolation_face        => lagrangian_reference_fe_update_interpolation_face
     procedure :: get_component_node               => lagrangian_reference_fe_get_component_node
     procedure :: get_scalar_from_vector_node      => lagrangian_reference_fe_get_scalar_from_vector_node
     procedure :: get_number_nodes_scalar          => lagrangian_reference_fe_get_number_nodes_scalar
     procedure :: get_value_scalar                 => lagrangian_reference_fe_get_value_scalar
     procedure :: get_value_vector                 => lagrangian_reference_fe_get_value_vector
     procedure :: get_gradient_scalar              => lagrangian_reference_fe_get_gradient_scalar
     procedure :: get_gradient_vector              => lagrangian_reference_fe_get_gradient_vector
     procedure :: get_divergence_vector            => lagrangian_reference_fe_get_divergence_vector
     procedure :: get_curl_vector                  => lagrangian_reference_fe_get_curl_vector
     procedure :: interpolate_nodal_values         => lagrangian_reference_fe_interpolate_nodal_values
     procedure :: set_nodal_quadrature             => lagrangian_reference_fe_set_nodal_quadrature
     procedure :: set_scalar_field_to_nodal_values => lagrangian_reference_fe_set_scalar_field_to_nodal_values
     procedure :: set_vector_field_to_nodal_values => lagrangian_reference_fe_set_vector_field_to_nodal_values
     procedure :: set_tensor_field_to_nodal_values => lagrangian_reference_fe_set_tensor_field_to_nodal_values
     procedure :: evaluate_fe_function_scalar      => lagrangian_reference_fe_evaluate_fe_function_scalar
     procedure :: evaluate_fe_function_vector      => lagrangian_reference_fe_evaluate_fe_function_vector
     procedure :: evaluate_fe_function_tensor      => lagrangian_reference_fe_evaluate_fe_function_tensor
     procedure :: get_number_subelements           => lagrangian_reference_fe_get_number_subelements
     procedure :: free                             => lagrangian_reference_fe_free
     ! Concrete TBPs of this derived data type
     procedure :: fill                             => lagrangian_reference_fe_fill
     procedure :: fill_field_components            => lagrangian_reference_fe_fill_field_components
     procedure :: fill_permutation_array           => lagrangian_reference_fe_fill_permutation_array
     procedure :: get_node_coordinates_array       => lagrangian_reference_fe_get_node_coordinates_array
     procedure :: set_permutation_1D               => lagrangian_reference_fe_set_permutation_1D
     procedure :: extend_list_components           => lagrangian_reference_fe_extend_list_components
     procedure :: apply_femap_to_interpolation     => lagrangian_reference_fe_apply_femap_to_interpolation
  end type lagrangian_reference_fe_t

  abstract interface
  
     subroutine fill_scalar_interface ( this )
     import :: lagrangian_reference_fe_t
       implicit none 
       class(lagrangian_reference_fe_t), intent(inout) :: this 
     end subroutine fill_scalar_interface
     
     subroutine fill_quadrature_interface ( this, quadrature )
     import :: lagrangian_reference_fe_t, quadrature_t
       implicit none 
       class(lagrangian_reference_fe_t), intent(in)    :: this
       type(quadrature_t)              , intent(inout) :: quadrature       
     end subroutine fill_quadrature_interface
     
     subroutine fill_nodal_quadrature_interface ( this, quadrature, order )
     import :: lagrangian_reference_fe_t, quadrature_t, ip
       implicit none 
       class(lagrangian_reference_fe_t), intent(in)    :: this
       type(quadrature_t)              , intent(inout) :: quadrature
       integer(ip)                     , intent(in)    :: order
     end subroutine fill_nodal_quadrature_interface
     
     subroutine fill_interpolation_interface ( this, interpolation, order, coord_ip )
     import :: lagrangian_reference_fe_t, interpolation_t, ip, rp
       implicit none 
       class(lagrangian_reference_fe_t), intent(in)    :: this
       type(interpolation_t)           , intent(inout) :: interpolation
       integer(ip)                     , intent(in)    :: order   
       real(rp)                        , intent(in)    :: coord_ip(:,:)
     end subroutine fill_interpolation_interface
 
     subroutine fill_face_interpolation_interface ( this,               &
                                                    face_interpolation, &
                                                    local_quadrature,   &
                                                    local_face_id )
     import :: lagrangian_reference_fe_t, interpolation_t, quadrature_t, ip
       implicit none 
       class(lagrangian_reference_fe_t), intent(in)    :: this
       type(interpolation_t)           , intent(inout) :: face_interpolation
       type(quadrature_t)              , intent(in)    :: local_quadrature
       integer(ip)                     , intent(in)    :: local_face_id
     end subroutine fill_face_interpolation_interface
     
     function get_number_interior_points_x_dim_interface ( this,                   &
                                                           number_interior_points, &
                                                           dimension)
     import :: lagrangian_reference_fe_t, ip
       implicit none
       class(lagrangian_reference_fe_t), intent(in)    :: this
       integer(ip)                     , intent(in)    :: number_interior_points
       integer(ip)                     , intent(in)    :: dimension
       integer(ip) :: get_number_interior_points_x_dim_interface
     end function get_number_interior_points_x_dim_interface
     
     function local_coordinates_to_local_id_interface ( this,                 &
                                                        local_coordinates,    &
                                                        number_of_dimensions, &
                                                        order )
     import :: lagrangian_reference_fe_t, ip
       implicit none
       class(lagrangian_reference_fe_t), intent(in)    :: this
       integer(ip)                     , intent(in)    :: local_coordinates(:)
       integer(ip)                     , intent(in)    :: number_of_dimensions
       integer(ip)                     , intent(in)    :: order
       integer(ip) :: local_coordinates_to_local_id_interface
     end function local_coordinates_to_local_id_interface
     
     subroutine local_id_to_local_coordinates_interface( this,                 &
                                                         local_coordinates,    &
                                                         local_id,             &
                                                         number_of_dimensions, &
                                                         order )
     import :: lagrangian_reference_fe_t, ip
       implicit none
       class(lagrangian_reference_fe_t), intent(in)    :: this
       integer(ip)                     , intent(inout) :: local_coordinates(:)
       integer(ip)                     , intent(in)    :: local_id
       integer(ip)                     , intent(in)    :: number_of_dimensions
       integer(ip)                     , intent(in)    :: order       
     end subroutine local_id_to_local_coordinates_interface

     subroutine set_coordinates_1D_interface (this, abscissae, number_of_points)
     import :: lagrangian_reference_fe_t, ip, rp
       implicit none
       class(lagrangian_reference_fe_t), intent(in)    :: this
       integer(ip)                     , intent(in)    :: number_of_points
       real(rp)                        , intent(inout) :: abscissae(:)
     end subroutine set_coordinates_1D_interface
     
     subroutine set_permutation_2D_interface ( this,               &
                                               permutation,        &
                                               number_nodes_x_dim, &
                                               orientation,        &
                                               rotation )
     import :: lagrangian_reference_fe_t, ip
       implicit none 
       class(lagrangian_reference_fe_t), intent(in)    :: this
       integer(ip)                     , intent(inout) :: permutation(:)
       integer(ip)                     , intent(in)    :: number_nodes_x_dim
       integer(ip)                     , intent(in)    :: orientation
       integer(ip)                     , intent(in)    :: rotation
     end subroutine set_permutation_2D_interface
     
     function set_number_quadrature_points_interface ( this, order, dimension )
     import :: lagrangian_reference_fe_t, ip
       implicit none 
       class(lagrangian_reference_fe_t), intent(in)    :: this
       integer(ip)                     , intent(in)    :: order    
       integer(ip)                     , intent(in)    :: dimension
       integer(ip) :: set_number_quadrature_points_interface
     end function set_number_quadrature_points_interface
     
     function compute_number_nodes_scalar_interface ( this, order, dimension )
     import :: lagrangian_reference_fe_t, ip
       implicit none 
       class(lagrangian_reference_fe_t), intent(in)    :: this
       integer(ip)                     , intent(in)    :: order    
       integer(ip)                     , intent(in)    :: dimension
       integer(ip) :: compute_number_nodes_scalar_interface
     end function compute_number_nodes_scalar_interface

  end interface
  
  public :: lagrangian_reference_fe_t  
  
  !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  type, extends(lagrangian_reference_fe_t) :: quad_lagrangian_reference_fe_t
     private
   contains 
     ! Deferred TBP implementors from reference_fe_t
     procedure :: check_compatibility_of_vefs      => quad_lagrangian_reference_fe_check_compatibility_of_vefs
     procedure :: get_characteristic_length        => quad_lagrangian_reference_fe_get_characteristic_length
     procedure :: get_subelements_connectivity     => quad_lagrangian_reference_fe_get_subelements_connectivity
     ! Deferred TBP implementors from lagrangian_reference_fe_t
     procedure :: fill_scalar                      => quad_lagrangian_reference_fe_fill_scalar
     procedure :: fill_quadrature                  => quad_lagrangian_reference_fe_fill_quadrature
     procedure :: fill_nodal_quadrature            => quad_lagrangian_reference_fe_fill_nodal_quadrature
     procedure :: fill_interpolation               => quad_lagrangian_reference_fe_fill_interpolation
     procedure :: fill_face_interpolation          => quad_lagrangian_reference_fe_fill_face_interpolation
     procedure :: local_coordinates_to_local_id    => quad_lagrangian_reference_fe_local_coordinates_to_local_id
     procedure :: local_id_to_local_coordinates    => quad_lagrangian_reference_fe_local_id_to_local_coordinates
     procedure :: set_coordinates_1D               => quad_lagrangian_reference_fe_set_coordinates_1D
     procedure :: set_permutation_2D               => quad_lagrangian_reference_fe_set_permutation_2D
     procedure :: set_number_quadrature_points     => quad_lagrangian_reference_fe_set_number_quadrature_points
     procedure :: compute_number_nodes_scalar      => quad_lagrangian_reference_fe_compute_number_nodes_scalar
     procedure :: get_number_interior_points_x_dim => quad_lagrangian_reference_fe_get_number_interior_points_x_dim
     ! Concrete TBPs of this derived data type
     procedure :: evaluate_interpolation_1D        => quad_lagrangian_reference_fe_evaluate_interpolation_1D 
     procedure :: evaluate_interpolation           => quad_lagrangian_reference_fe_evaluate_interpolation 
     procedure :: evaluate_face_interpolation      => quad_lagrangian_reference_fe_evaluate_face_interpolation
  end type quad_lagrangian_reference_fe_t
  
  public :: quad_lagrangian_reference_fe_t

!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  type, extends(lagrangian_reference_fe_t) :: tri_lagrangian_reference_fe_t
     private
   contains 
     ! Deferred TBP implementors from reference_fe_t
     procedure :: check_compatibility_of_vefs       => tri_lagrangian_reference_fe_check_compatibility_of_vefs
     procedure :: get_characteristic_length         => tri_lagrangian_reference_fe_get_characteristic_length
     procedure :: get_subelements_connectivity      => tri_lagrangian_reference_fe_get_subelements_connectivity
     ! Deferred TBP implementors from lagrangian_reference_fe_t
     procedure :: fill_scalar                       => tri_lagrangian_reference_fe_fill_scalar
     procedure :: fill_quadrature                   => tri_lagrangian_reference_fe_fill_quadrature
     procedure :: fill_nodal_quadrature             => tri_lagrangian_reference_fe_fill_nodal_quadrature
     procedure :: fill_interpolation                => tri_lagrangian_reference_fe_fill_interpolation
     procedure :: fill_face_interpolation           => tri_lagrangian_reference_fe_fill_face_interpolation
     procedure :: local_coordinates_to_local_id     => tri_lagrangian_reference_fe_local_coordinates_to_local_id
     procedure :: local_id_to_local_coordinates     => tri_lagrangian_reference_fe_local_id_to_local_coordinates
     procedure :: set_coordinates_1D                => tri_lagrangian_reference_fe_set_coordinates_1D
     procedure :: set_permutation_2D                => tri_lagrangian_reference_fe_set_permutation_2D
     procedure :: set_number_quadrature_points      => tri_lagrangian_reference_fe_set_number_quadrature_points
     procedure :: compute_number_nodes_scalar       => tri_lagrangian_reference_fe_compute_number_nodes_scalar
     procedure :: get_number_interior_points_x_dim  => tri_lagrangian_reference_fe_get_number_interior_points_x_dim
     ! Concrete TBPs of this derived data type
     procedure :: fill_nodes_vef                    => tri_lagrangian_reference_fe_fill_nodes_vef
     procedure :: fill_vef_dimension_and_vertices   => tri_lagrangian_reference_fe_fill_vef_dimension_and_vertices
     procedure :: get_vef_orientation               => tri_lagrangian_reference_fe_get_vef_orientation
     procedure :: compute_number_interior_nodes     => tri_lagrangian_reference_fe_compute_number_interior_nodes
     procedure :: compute_sum_of_nodes_in_simplices => tri_lagrangian_reference_fe_compute_sum_of_nodes_in_simplices
     procedure :: evaluate_interpolation            => tri_lagrangian_reference_fe_evaluate_interpolation
  end type tri_lagrangian_reference_fe_t
  
  public :: tri_lagrangian_reference_fe_t

!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

type volume_integrator_t 
  private
  integer(ip)                    :: number_shape_functions
  integer(ip)                    :: number_quadrature_points
  class(reference_fe_t), pointer :: reference_fe
  type(interpolation_t)          :: interpolation      ! Unknown interpolation_t in the reference element domain
  type(interpolation_t)          :: interpolation_o_map! Unknown interpolation_t in the physical element domain
contains

  procedure, non_overridable :: create => volume_integrator_create
  procedure, non_overridable :: free   => volume_integrator_free
  procedure, non_overridable :: update => volume_integrator_update
  procedure, non_overridable :: print  => volume_integrator_print
  
  procedure, non_overridable :: get_interpolation_reference_cell =>                               &
       &                                   volume_integrator_get_interpolation_reference_cell
  procedure, non_overridable :: get_interpolation_real_cell =>                                    &
       &                                   volume_integrator_get_interpolation_real_cell


  procedure, non_overridable, private :: get_value_scalar           => volume_integrator_get_value_scalar
  procedure, non_overridable, private :: get_value_vector           => volume_integrator_get_value_vector
  procedure, non_overridable, private :: get_value_tensor           => volume_integrator_get_value_tensor
  procedure, non_overridable, private :: get_value_symmetric_tensor => volume_integrator_get_value_symmetric_tensor
  generic            :: get_value => get_value_scalar, &
                                     get_value_vector, &
                                     get_value_tensor, &
                                     get_value_symmetric_tensor
    
  procedure, non_overridable, private :: get_gradient_scalar => volume_integrator_get_gradient_scalar
  procedure, non_overridable, private :: get_gradient_vector => volume_integrator_get_gradient_vector
  generic                             :: get_gradient => get_gradient_scalar, &
                                                         get_gradient_vector 

  procedure, non_overridable, private :: get_symmetric_gradient_vector => volume_integrator_get_symmetric_gradient_vector
  generic                             :: get_symmetric_gradient => get_symmetric_gradient_vector
  
  procedure, non_overridable, private :: get_divergence_vector => volume_integrator_get_divergence_vector
  procedure, non_overridable, private :: get_divergence_tensor => volume_integrator_get_divergence_tensor
  generic                             :: get_divergence => get_divergence_vector, &
                                                           get_divergence_tensor

														   procedure, non_overridable, private :: get_curl_vector => volume_integrator_get_curl_vector
  generic                             :: get_curl => get_curl_vector
  
  ! We might want to have the following in the future:
  !  (x) get_hessian (scalar,vector)
  !  (x) get_third_derivative (scalar,vector)
  ! But note that in such a case we would require higher-to-2 rank tensors
  ! (i.e., type(tensor_field_t) is a rank-2 tensor)
  
  procedure, non_overridable, private :: volume_integrator_evaluate_fe_function_scalar
  procedure, non_overridable, private :: volume_integrator_evaluate_fe_function_vector
  procedure, non_overridable, private :: volume_integrator_evaluate_fe_function_tensor
  generic :: evaluate_fe_function => volume_integrator_evaluate_fe_function_scalar, &
                                   & volume_integrator_evaluate_fe_function_vector, &
                                   & volume_integrator_evaluate_fe_function_tensor

end type volume_integrator_t

type p_volume_integrator_t
  type(volume_integrator_t), pointer :: p => NULL() 
contains
  procedure :: allocate => p_volume_integrator_allocate 
  procedure :: free     => p_volume_integrator_free
end type p_volume_integrator_t

public :: volume_integrator_t, p_volume_integrator_t

!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

type face_map_t
   private
   logical                         :: is_boundary
   type(fe_map_t)                  :: face_map
   type(fe_map_face_restriction_t) :: fe_maps(2)
   integer(ip)                     :: number_dimensions
 contains
   procedure, non_overridable :: create               => face_map_create
   procedure, non_overridable :: free                 => face_map_free
   procedure, non_overridable :: update               => face_map_update
   procedure, non_overridable :: compute_characteristic_length                                      &
        &                                             => face_map_compute_characteristic_length
   procedure, non_overridable :: get_quadrature_coordinates                                         &
        &                                             => face_map_get_quadrature_coordinates
   procedure, non_overridable :: get_face_coordinates => face_map_get_face_coordinates
   procedure, non_overridable :: get_coordinates_neighbour                                          &
        &                                             => face_map_get_coordinates_neighbour
   procedure, non_overridable :: get_neighbour_fe_map => face_map_get_neighbour_fe_map
   procedure, non_overridable :: get_normals          => face_map_get_normals
   procedure, non_overridable :: get_det_jacobian     => face_map_get_det_jacobian
end type face_map_t

public :: face_map_t

!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

type face_integrator_t
   private
   logical                                :: is_boundary
   type(interpolation_face_restriction_t) :: interpolation_face_restriction(2)
   type(p_reference_fe_t)                 :: reference_fe(2)
   integer(ip)                            :: current_qpoints_perm_cols(2)
   integer(ip), allocatable               :: qpoints_perm(:,:)
 contains
   procedure, non_overridable :: create            => face_integrator_create
   procedure, non_overridable :: update            => face_integrator_update
   procedure, non_overridable :: free              => face_integrator_free
   procedure, non_overridable :: get_value_scalar  => face_integrator_get_value_scalar
   generic                    :: get_value         => get_value_scalar
   procedure, non_overridable :: get_gradient_scalar  => face_integrator_get_gradient_scalar
   generic                    :: get_gradient => get_gradient_scalar
end type face_integrator_t

type p_face_integrator_t
  type(face_integrator_t)          , pointer :: p => NULL()
end type p_face_integrator_t

public :: face_integrator_t, p_face_integrator_t

!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

contains

  ! Includes with all the TBP and supporting subroutines for the types above.
  ! In a future, we would like to use the submodule features of FORTRAN 2008.

#include "sbm_quadrature.i90"

#include "sbm_interpolation.i90"

#include "sbm_reference_fe.i90"

#include "sbm_lagrangian_reference_fe.i90"

#include "sbm_quad_lagrangian_reference_fe.i90"

#include "sbm_tri_lagrangian_reference_fe.i90"

#include "sbm_volume_integrator.i90"

#include "sbm_face_integrator.i90"

end module reference_fe_names
