
#ifdef ENABLE_QHULL

#include <libqhull.h>

int delaunay_init_and_compute( int dim, int numpoints, coordT *points, int* numcells )
{

  // Set options
  boolT ismalloc = False;
  FILE *outfile= fopen("/dev/null","w");
  //FILE *outfile= stdout;
  FILE *errfile= stderr;
  char flags[250];
  if (dim <= 3)
    sprintf(flags,"qhull d Qt Qbb Qc Qz");
  else
    sprintf(flags,"qhull d Qt Qbb Qc Qx");

  // Run qhull
  int exitcode = qh_new_qhull (dim, numpoints, points, ismalloc, flags, outfile, errfile);
  if (exitcode) return exitcode;

  // Triangulate all the non-simplex cells generated by qhull
  qh_triangulate ();

  // Count number of generated cells and double check that they are simplex
  facetT *facet;
  (*numcells) = 0;
  FORALLfacets
    {
      if (! facet->upperdelaunay) (*numcells)++;
      if (! facet->simplicial) return -1;
    }

  return 0;
}

int delaunay_fill_cells(int dim, int num_cells, int *cells )
{

  // Fill-in the cells connectivities
  int icell = 0;
  facetT *facet;
  vertexT *vertex, **vertexp;
  FORALLfacets
  {
    if (! facet->upperdelaunay)
      {
        int ivertex = 0;
        FOREACHvertex_ (facet->vertices)
          {
            cells[(dim+1)*icell+ivertex] = 1 + qh_pointid(vertex->point);
            ivertex++;
          }
        icell++;
      }
  }

  return 0;
}

int delaunay_free()
{

  // Free memory from qhull and check that no memory is leaked
  qh_freeqhull (! qh_ALL);
  int curlong, totlong;
  qh_memfreeshort (&curlong, &totlong);
  if (curlong || totlong) return -2;

  return 0;
}

#endif
