#!/bin/bash
script_dir=$(dirname ${BASH_SOURCE[0]})
threads_per_task=1  #change subdomains per node below if more than one thread is used per rank
coarse_tasks=1      # only 0 or 1 possible, goes in a separate node
threads_last_task=48
max_wall_time=20
name=poisson

num_one_h_local=2
lst_one_h_local="30#40"

num_k=5
lst_k="1#2#3#4#5"

id_k=1
while [ $id_k -le $num_k ]
do
   k=$(echo $lst_k | cut -f$id_k -d#)
   NPARTX=$(( 4 * $k))
   NPARTY=$(( 4 * $k))
   NPARTZ=$(( 3 * $k))

   tasks=$(( 48 * $k + $coarse_tasks ))
   nodes=$(( $k + $coarse_tasks ))
   
   id_one_h=1
   while [ $id_one_h -le $num_one_h_local ] 
   do
     one_h_loc=$(echo $lst_one_h_local|cut -f$id_one_h -d#)
     NX=$(( $one_h_loc * $k))
     NY=$(( $NX * 4))
     NZ=$(( $NX * 3))
     NX=$(( $NX * 4))
     identifier="$name"_"$NX"_"$NY"_"$NZ"_"$NPARTX"_"$NPARTY"_"$NPARTZ"

     cat $script_dir/parametrized_command_template | sed "s:NX:$NX:g" | sed "s:NY:$NY:g" | sed "s:NZ:$NZ:g" > $script_dir/command_template
     echo $script_dir/run -i $name -n $nodes -t $tasks --num_threads_per_task $threads_per_task  --num_threads_last_task $threads_last_task -w $max_wall_time 
     $script_dir/run -i $name -n $nodes -t $tasks --num_threads_per_task $threads_per_task  --num_threads_last_task $threads_last_task -w $max_wall_time 

     let id_one_h=id_one_h+1
   done
   let id_k=id_k+1 
done

